/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is normally generated by `next dev`/`next build`. It is
// committed so `tsc --noEmit` works in a fresh checkout and in CI before the
// first build has run.
